export interface AppTheme {
  background: string
  foreground: string
  card: string
  cardForeground: string
  popover: string
  popoverForeground: string
  primary: string
  primaryForeground: string
  secondary: string
  secondaryForeground: string
  muted: string
  mutedForeground: string
  accent: string
  accentForeground: string
  destructive: string
  destructiveForeground: string
  success: string
  successForeground: string
  info: string
  infoForeground: string
  highlight: string
  highlightForeground: string
  border: string
  border4: string
  input: string
  ring: string
  sidebar: string
  sidebarForeground: string
  sidebarPrimary: string
  sidebarPrimaryForeground: string
  sidebarAccent: string
  sidebarAccentForeground: string
  sidebarBorder: string
  sidebarRing: string
  chart1: string
  chart2: string
  chart3: string
  chart4: string
  chart5: string
  activeStatus: string
  activeStatusForeground: string
  inactiveStatus: string
  inactiveStatusForeground: string
  pendingStatus: string
  pendingStatusForeground: string
  radii: Record<string, number>
  spacing: Record<number, number>
  isDark: boolean
}
